routes/web.php
<?php

Route::get('/', 'StaticPagesController@home')->name('home');
Route::get('/help', 'StaticPagesController@help')->name('help');
Route::get('/about', 'StaticPagesController@about')->name('about');

Route::get('signup', 'UsersController@create')->name('signup');
Route::resource('users', 'UsersController');

Route::get('login', 'SessionsController@create')->name('login');
Route::post('login', 'SessionsController@store')->name('login');
Route::delete('logout', 'SessionsController@destroy')->name('logout');

Route::get('signup/confirm/{token}', 'UsersController@confirmEmail')->name('confirm_email');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::resource('statuses', 'StatusesController', ['only' => ['store', 'update', 'destroy']]);

Route::get('/users/{user}/followings', 'UsersController@followings')->name('users.followings');
Route::get('/users/{user}/followers', 'UsersController@followers')->name('users.followers');

Route::post('/users/followers/{user}', 'FollowersController@store')->name('followers.store');
Route::delete('/users/followers/{user}', 'FollowersController@destroy')->name('followers.destroy');




//  Demo router
Route::group(['prefix' => 'demo', 'namespace' => 'Demo',], function () {
        Route::resource('/', 'DemoController');
        Route::resource('cache', 'CacheController');
        Route::resource('event', 'EventController');
        Route::resource('file', 'FileController');
        Route::resource('jobs', 'JobsController');
        Route::resource('notification', 'NotificationController');
        Route::resource('schedule', 'ScheduleController');





    }
);

resources/views/layouts/_footer.blade.php
<div class="col-md-12">
  <footer class="footer">
      footer
      <ul>
        <li><a href="{{ route('about') }}">page1</a></li>
        <li><a href="{{ route('about') }}">page2</a></li>
        <li><a href="{{ route('about') }}">About</a></li>
      </ul>
  </footer>
</div>

resources/views/layouts/_header.blade.php
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="col-md-offset-1 col-md-10">
      <a href="/" id="logo"> Logo</a>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          @if (Auth::check())
            <li><a href="{{ route('users.index') }}">All Users</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                {{ Auth::user()->name }} <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{{ route('users.show', Auth::user()->id) }}">Personal center</a></li>
                <li><a href="{{ route('users.edit', Auth::user()->id) }}">edit information</a></li>
                <li class="divider"></li>
                <li>
                  <a id="logout" href="#">
                    <form action="{{ route('logout') }}" method="POST">
                      {{ csrf_field() }}
                      {{ method_field('DELETE') }}
                      <button class="btn btn-block btn-danger" type="submit" name="button">Sign out</button>
                    </form>
                  </a>
                </li>
              </ul>
            </li>
          @else
            <li><a href="{{ route('help') }}">Help</a></li>
            <li><a href="{{ route('login') }}">Log in</a></li>
          @endif
        </ul>
      </nav>
    </div>
  </div>
</header>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>@yield('title', 'Sample App') - jh-Laravel</title>
    <link rel="stylesheet" href="{{ env('APP_URL') }}/css/app.css">
    <meta name="csrf-token" content="{{ csrf_token() }}">
  </head>
  <body>
    @include('layouts._header')

    <div class="container">
      <div class="col-md-offset-1 col-md-10">
        @include('shared._messages')
        @yield('content')
        @include('layouts._footer')
      </div>
    </div>


    <script src="{{ env('APP_URL') }}/js/app.js"></script>
  </body>
</html>